workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 90
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ruteromde.app
      groups:
        - rutero-secrets
      vars:
        BUNDLE_ID: "com.ruteromde.app"
        APP_STORE_APP_ID: "6739584898"
    scripts:
      - name: Set up GoogleService-Info.plist
        script: |
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Flutter pub get
        script: |
          flutter pub get
      - name: Pod install
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
