// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaC-aTKIUg_gYEE7QDcb2_-d5uZrhePsI',
    appId: '1:300771058852:web:1b21fe476d0268defc3231',
    messagingSenderId: '300771058852',
    projectId: 'rutero-mde',
    authDomain: 'rutero-mde.firebaseapp.com',
    storageBucket: 'rutero-mde.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA37snNyEz7h-mOXcar1pnsNnzBntSbFTg',
    appId: '1:300771058852:android:d89b55f65692168bfc3231',
    messagingSenderId: '300771058852',
    projectId: 'rutero-mde',
    storageBucket: 'rutero-mde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4D3nwkeJqNr8jof0l7gB__1GNs1OKe80',
    appId: '1:300771058852:ios:25061151515af895fc3231',
    messagingSenderId: '300771058852',
    projectId: 'rutero-mde',
    storageBucket: 'rutero-mde.firebasestorage.app',
    androidClientId: '300771058852-876d0uftjrbbji94k1b0u1j79ebac3k3.apps.googleusercontent.com',
    iosClientId: '300771058852-nlj5rrvtbvi70fk2lpi8r8qjqbigh87t.apps.googleusercontent.com',
    iosBundleId: 'com.example.ruteroMde',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4D3nwkeJqNr8jof0l7gB__1GNs1OKe80',
    appId: '1:300771058852:ios:25061151515af895fc3231',
    messagingSenderId: '300771058852',
    projectId: 'rutero-mde',
    storageBucket: 'rutero-mde.firebasestorage.app',
    androidClientId: '300771058852-876d0uftjrbbji94k1b0u1j79ebac3k3.apps.googleusercontent.com',
    iosClientId: '300771058852-nlj5rrvtbvi70fk2lpi8r8qjqbigh87t.apps.googleusercontent.com',
    iosBundleId: 'com.example.ruteroMde',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaC-aTKIUg_gYEE7QDcb2_-d5uZrhePsI',
    appId: '1:300771058852:web:c79fd3c73915a90ffc3231',
    messagingSenderId: '300771058852',
    projectId: 'rutero-mde',
    authDomain: 'rutero-mde.firebaseapp.com',
    storageBucket: 'rutero-mde.firebasestorage.app',
  );
}
